CREATE DATABASE DuAn1Nhom102
GO
USE DuAn1Nhom102
--1.TABLE KHÁCH HÀNG
CREATE TABLE Khach_Hang
	(
		IdKH UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
		MaKH VARCHAR(20) UNIQUE NOT NULL,
		Ho NVARCHAR(20) DEFAULT NULL,
		TenDem NVARCHAR(100) DEFAULT NULL,
		Ten NVARCHAR(20) DEFAULT NULL,
		GioiTinh NVARCHAR(20) DEFAULT NULL,
		NgaySinh DATE DEFAULT NULL,
		Sdt VARCHAR(15) DEFAULT NULL,
		DiaChi NVARCHAR(150) DEFAULT NULL,
		ThanhPho NVARCHAR(100) DEFAULT NULL,
		QuocGia NVARCHAR(100) DEFAULT NULL,
		TrangThai INT DEFAULT 0
	)
--2.TABLE BÀN
CREATE TABLE Ban
	(
		IdBan UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
		IdKhuVuc UNIQUEIDENTIFIER NOT NULL,
		MaBan INT UNIQUE NOT NULL,
		SoLuongChoNgoi INT NOT NULL,
		TrangThai INT DEFAULT 0
	)
--3.Thêm bảng Khu vực (3)
CREATE TABLE Khu_Vuc
	(
		IdKhuVuc UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
		MaKhuVuc VARCHAR(20) UNIQUE NOT NULL,
		TenKhuVuc NVARCHAR(100) NOT NULL,
		TrangThai INT DEFAULT 0
	)
--4.Hoá Đơn
CREATE TABLE Hoa_Don
	(
		IdHD UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
		IdNV UNIQUEIDENTIFIER NOT NULL,
		IdKH UNIQUEIDENTIFIER DEFAULT NULL,
		IdBan UNIQUEIDENTIFIER NOT NULL,
		MaHD VARCHAR(20) UNIQUE NOT NULL,
		NgayTao DATE NOT NULL,
		NgayThanhToan DATE DEFAULT NULL,
		TongTien DECIMAL(20,0) DEFAULT 0,
		GhiChu NVARCHAR(200) DEFAULT NULL,
		TrangThai INT DEFAULT 0
	)
	--5.Giao dịch
CREATE TABLE Giao_Dich
	(
		Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
		IdHD UNIQUEIDENTIFIER NOT NULL,
		HinhThucThanhToan NVARCHAR(200) NOT NULL,
		SoTienThanhToan DECIMAL(20,0) DEFAULT 0
	)
--6.Combo --run r nma có cần thêm số combo sẽ bán ko-- ko cần thêm đâu ngu shiii
CREATE TABLE Combo
	(
		IdCombo UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
		IdNV UNIQUEIDENTIFIER NOT NULL,
		MaCB VARCHAR(20) UNIQUE NOT NULL,
		TenCB NVARCHAR(150) NOT NULL,
		HinhAnh VARCHAR(255) DEFAULT NULL,
		DonGia DECIMAL(20,0) NOT NULL,
		TrangThai INT DEFAULT 0
	)
--7.Chi_Tiet_Combo
CREATE TABLE  Chi_Tiet_Combo
	(
		Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
		IdCombo UNIQUEIDENTIFIER NOT NULL,
		IdMonAn UNIQUEIDENTIFIER NOT NULL,
		SoLuongMonAn INT NOT NULL,
	)
--8.Hoa_Don_Chi_Tiet 
CREATE TABLE Hoa_Don_Chi_Tiet
	(
		IdHDCT UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
		IdMonAn UNIQUEIDENTIFIER DEFAULT NULL, 
		IdHD UNIQUEIDENTIFIER NOT NULL,
		IdCombo UNIQUEIDENTIFIER DEFAULT NULL,
		SoLuongMonAn INT NOT NULL,
		DonGiaMonAn DECIMAL(20,0) NOT NULL,
		SoLuongCombo INT NOT NULL,
		DonGiaCombo DECIMAL(20,0) NOT NULL
	)
--9.Nhan_Vien
CREATE TABLE Nhan_Vien
	(
		IdNV UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
		IdCV UNIQUEIDENTIFIER NOT NULL,
		MaNV VARCHAR(20) UNIQUE NOT NULL,
		Ho NVARCHAR(20) NOT NULL,
		TenDem NVARCHAR(100) NOT NULL,
		Ten NVARCHAR(20) NOT NULL,
		GioiTinh NVARCHAR(20) DEFAULT NULL,
		Sdt VARCHAR(15) NOT NULL,
		NgaySinh DATE NOT NULL,
		DiaChi NVARCHAR(200) NOT NULL,
		MatKhau VARCHAR(70) NOT NULL,
		TrangThai INT DEFAULT 0
	)
--10.Mon_An
CREATE TABLE Mon_An 
	(
		IdMonAn UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
		IdLoai UNIQUEIDENTIFIER NOT NULL,
		MaMonAn VARCHAR(20) UNIQUE NOT NULL,
		TenMonAn NVARCHAR(150) NOT NULL,
		HinhAnh VARCHAR(255) DEFAULT NULL,
		DonGia DECIMAL(20,0) NOT NULL,
		DonViTinh NVARCHAR(50) NOT NULL,
		TrangThai INT DEFAULT 0
	)
--11.Khuyen_Mai_Chi_Tiet 
CREATE TABLE Khuyen_Mai_Chi_Tiet
	(
		IdCTKM UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
		IdMonAn UNIQUEIDENTIFIER NOT NULL,
		IdKM UNIQUEIDENTIFIER NOT NULL,
	)
--12.KhuyenMai 
CREATE TABLE Khuyen_Mai
	(
		IdKM UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
		IdNV UNIQUEIDENTIFIER NOT NULL,
		MaKM VARCHAR(20) UNIQUE NOT NULL,
		TenKM NVARCHAR(50) NOT NULL,
		ThoiGianBD DATE NOT NULL,
		ThoiGianKT DATE NOT NULL,
		LoaiKM NVARCHAR(50) NOT NULL,
		GtriKM DECIMAL(20,0) DEFAULT 0,
		GhiChu NVARCHAR(200) DEFAULT NULL,
		TrangThai INT DEFAULT 0 
	)
----11. Ca_Lam_Viec
--CREATE TABLE Ca_Lam_Viec
--	(
--		IdCaLamViec UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
--		IdNV UNIQUEIDENTIFIER NOT NULL,
--		TgianBD DATETIME NOT NULL,
--		TgianKT DATETIME DEFAULT NULL,
--		TienDauCa DECIMAL(20,0) DEFAULT 0,
--		TienMatTaiQuan DECIMAL(20,0) NOT NULL,
--		TienNhoThuHo DECIMAL(20,0) DEFAULT 0,
--		GhiChu NVARCHAR(200)
--	)

--13.Chuc_Vu
CREATE TABLE Chuc_Vu
	(
		IdCV UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
		MaCV VARCHAR(20) UNIQUE NOT NULL,
		TenCV NVARCHAR(100) NOT NULL,
		TrangThai INT DEFAULT 0
	)
--14.Danh mục
CREATE TABLE Danh_Muc
	(
		IdDanhMuc UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
		IdLoai UNIQUEIDENTIFIER,
		MaDanhMuc VARCHAR(20) UNIQUE NOT NULL,
		TenDanhMuc NVARCHAR(200) NOT NULL,
		TrangThai INT DEFAULT 0
	)
---Quan hệ giữua các bảng:
-------đệ quy bảng danh mục:
ALTER TABLE Danh_Muc ADD CONSTRAINT FK_Loai FOREIGN KEY(IdLoai) REFERENCES Danh_Muc(IdDanhMuc)
--
ALTER TABLE Khuyen_Mai ADD CONSTRAINT FK_NVTaoKM FOREIGN KEY (IdNV) REFERENCES Nhan_Vien(IdNV)
ALTER TABLE Khuyen_Mai_Chi_Tiet ADD CONSTRAINT FK_MaKM FOREIGN KEY (IdKM) REFERENCES Khuyen_Mai(IdKM)
ALTER TABLE Khuyen_Mai_Chi_Tiet ADD CONSTRAINT FK_MonAnKM FOREIGN KEY (IdMonAn) REFERENCES Mon_An(IdMonAn)
ALTER TABLE Nhan_Vien ADD CONSTRAINT FK_CV FOREIGN KEY (IdCV) REFERENCES Chuc_Vu(IdCV)
ALTER TABLE Hoa_Don_Chi_Tiet ADD CONSTRAINT FK_MonAn_HDCT FOREIGN KEY(IdMonAn) REFERENCES Mon_An(IdMonAn)
ALTER TABLE Hoa_Don_Chi_Tiet ADD CONSTRAINT FK_HD_HDCT FOREIGN KEY(IdHD) REFERENCES Hoa_Don(IdHD)
ALTER TABLE Hoa_Don_Chi_Tiet ADD CONSTRAINT FK_Combo_HDCT FOREIGN KEY(IdCombo) REFERENCES Combo(IdCombo)
ALTER TABLE Chi_Tiet_Combo ADD CONSTRAINT FK_ComboCT FOREIGN KEY (IdCombo) REFERENCES Combo(IdCombo)
ALTER TABLE Chi_Tiet_Combo ADD CONSTRAINT FK_MonAnCombo FOREIGN KEY (IdMonAn) REFERENCES Mon_An(IdMonAn)
ALTER TABLE Hoa_Don ADD CONSTRAINT FK_Ban FOREIGN KEY(IdBan) REFERENCES Ban(IdBan)
ALTER TABLE Hoa_Don ADD CONSTRAINT FK_NV_HD FOREIGN KEY (IdNV) REFERENCES Nhan_Vien(IdNV)
ALTER TABLE Hoa_Don ADD CONSTRAINT FK_KH_HD FOREIGN KEY (IdKH) REFERENCES Khach_Hang(IdKH)
ALTER TABLE Combo ADD CONSTRAINT FK_NV_Combo FOREIGN KEY (IdNV) REFERENCES Nhan_Vien(IdNV)
ALTER TABLE Ban ADD CONSTRAINT FK_KhuVuc FOREIGN KEY(IdKhuVuc) REFERENCES Khu_Vuc(IdKhuVuc)
ALTER TABLE Mon_An ADD CONSTRAINT FK_Loai_monAN FOREIGN KEY(IdLoai) REFERENCES Danh_Muc(IdDanhMuc)
ALTER TABLE Giao_Dich ADD CONSTRAINT FK_HD FOREIGN KEY(IdHD) REFERENCES Hoa_Don(IdHD)